---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-100"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.project}}

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true

  source:
    chart: sealed-secrets
    # https://github.com/bitnami-labs/sealed-secrets/tree/main/helm/sealed-secrets
    repoURL: {{ .Values.repoUrl }}
    targetRevision: {{ .Values.chartVersion }}
    helm:
      valuesObject: 
        {{ .Values.sealedSecret | toYaml | nindent 8 }}

  destination:
    server: "https://kubernetes.default.svc"
    namespace: kube-system
